services:
  admin:
    image: "agent-sim-admin:latest"
    container_name: "admin"
    build:
      context: ./backend/admin/
    depends_on:
      rabbitmq:
        condition: service_healthy

  user:
    image: "agent-sim-user:latest"
    container_name: "user"
    build:
      context: ./backend/user/
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8081:8080

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 8080:15672
      - 5672:5672
    container_name: "rabbit-server"
    hostname: "localhost"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    hostname: localhost
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: company_sim
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  agents:
    image: "agent-sim-multiplexed-dev:latest"
    container_name: "agents"
    build:
      context: ./backend/multiplexed-agent/
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NUM_AGENTS: 7
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  vcs:
    image: "agent-sim-multiplexed-vc:latest"
    container_name: "vcs"
    build:
      context: ./backend/multiplexed-vc/
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NUM_AGENTS: 3
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  pgdata:
